# Site settings
title: Brian's Blog
email: brian@brianjohn.com
description: > # this means to ignore newlines until "baseurl:"
  The blog of Brian John. You're likely to find information related
  to programming and random other musings here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.brianjohn.com" # the base hostname & protocol for your site
twitter_username: brianpjohn
github_username:  f1sherman

# Build settings
markdown: kramdown
