name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '23 3 * * *'

concurrency:
  group: renovate
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub App token
        id: app_token
        uses: actions/create-github-app-token@v3.1.1
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
          repositories: ${{ github.event.repository.name }}

      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v44.0.3
        with:
          token: ${{ steps.app_token.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
